#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Open-source resource provided by Papercup Technologies Limited
# Author: Marlene Staib
# COMBILEX-TO-IPA MAPPING DICTIONARY FOR RP ENGLISH

combilex_to_ipa = {
    'Q': 'ɒ',
    's': 's',
    'r': 'ɹ',
    'p': 'p',
    'T': 'θ',
    'b': 'b',
    'N': 'ŋ',
    'u': 'u',
    'z': 'z',
    'v': 'v',
    'm': 'm',
    'm=': 'm̩',
    't': 't',
    '3': 'ɜ',
    'aU': 'aʊ',
    'k': 'k',
    'o~': 'ɔ̃',
    'S': 'ʃ',
    'Z': 'ʒ',
    'eI': 'ɛɪ',
    'OI': 'ɔɪ',
    'A': 'a',
    'D': 'ð',
    'I@': 'ɪə',
    '@': 'ə',
    'f': 'f',
    '@U': 'oʊ',
    'n=': 'n̩',
    'n': 'n',
    'w': 'w',
    'j': 'j',
    'h': 'h',
    'O': 'ɔ',
    'E': 'ɛ',
    'U@': 'ʊə',
    'I': 'ɪ',
    'E@': 'ɛə',
    'd': 'd',
    'V': 'ʌ',
    'tS': 'tʃ',
    'a': 'æ',
    'e~': 'ẽ',
    'l=': 'l̩',
    'i': 'i',
    'l': 'l',
    'g': 'g',
    'aI': 'aɪ',
    '5': 'ɫ',
    'dZ': 'dʒ',
    'U': 'ʊ'
}
