#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Open-source resource provided by Papercup Technologies Limited
# Author: Marlene Staib
# IPA-TO-PHONOLOGICAL FEATURES MAPPING DICTIONARY

# Stress markings need to be parsed from the specific dictionary resource used

ipa_to_phonemefeats = {
    '</s>': {'symbol_type': '</s>'},
    '</q>': {'symbol_type': '</q>'},
    '<sil>': {'symbol_type': '<sil>'},
    '<w>': {'symbol_type': '<w>'},
    '<s>': {'symbol_type': '<s>'},
    '+': {'symbol_type': '+'},  # magic 'e'; exists in combilex -- can be omitted
    'ɜ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'central',
          'vowel_openness': 'open-mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ˈɜ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'central',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'primary_stress'},
    'ˌɜ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'central',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'secondary_stress'},
    'ɫ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'lateral-approximant',
          'diacritic': 'velarized'},
    'ə': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'central',
          'vowel_openness': 'mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'a': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'open',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ˈa': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'open',
           'vowel_roundedness': 'unrounded',
           'stress': 'primary_stress'},
    'ˌa': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'open',
           'vowel_roundedness': 'unrounded',
           'stress': 'secondary_stress'},
    'ð': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'dental',
          'consonant_manner': 'fricative'},
    'ɛ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'open-mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ˈɛ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'primary_stress'},
    'ˌɛ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'secondary_stress'},
    'ɪ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front_central',
          'vowel_openness': 'close_close-mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ˈɪ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front_central',
           'vowel_openness': 'close_close-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'primary_stress'},
    'ˌɪ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front_central',
           'vowel_openness': 'close_close-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'secondary_stress'},
    'ŋ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'velar',
          'consonant_manner': 'nasal'},
    'ɔ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'back',
          'vowel_openness': 'open-mid',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ˈɔ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'back',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'rounded',
           'stress': 'primary_stress'},
    'ˌɔ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'back',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'rounded',
           'stress': 'secondary_stress'},
    'ɒ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'back',
          'vowel_openness': 'open',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ˈɒ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'back',
           'vowel_openness': 'open',
           'vowel_roundedness': 'rounded',
           'stress': 'primary_stress'},
    'ˌɒ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'back',
           'vowel_openness': 'open',
           'vowel_roundedness': 'rounded',
           'stress': 'secondary_stress'},
    'ɾ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'tap'},
    'ʃ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'postalveolar',
          'consonant_manner': 'fricative'},
    'θ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'dental',
          'consonant_manner': 'fricative'},
    'ʊ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'central_back',
          'vowel_openness': 'close_close-mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ˈʊ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'central_back',
           'vowel_openness': 'close_close-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'primary_stress'},
    'ˌʊ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'central_back',
           'vowel_openness': 'close_close-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'secondary_stress'},
    'ʌ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'back',
          'vowel_openness': 'open-mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ˈʌ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'back',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'primary_stress'},
    'ˌʌ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'back',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'secondary_stress'},
    'ʒ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'postalveolar',
          'consonant_manner': 'fricative'},
    'æ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'open-mid_open',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ˈæ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'open-mid_open',
           'vowel_roundedness': 'unrounded',
           'stress': 'primary_stress'},
    'ˌæ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'open-mid_open',
           'vowel_roundedness': 'unrounded',
           'stress': 'secondary_stress'},
    'b': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'bilabial',
          'consonant_manner': 'stop'},
    'd': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'stop'},
    'd͡ʒ': {'symbol_type': 'phoneme',
            'vowel_consonant': 'consonant',
            'VUV': 'voiced',
            'consonant_place': 'postalveolar',
            'consonant_manner': 'affricate'},
    'e': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'close-mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ˈe': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'close-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'primary_stress'},
    'ˌe': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'close-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'secondary_stress'},
    'ẽ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'unrounded',
           'stress': 'unstressed',
           'diacritic': 'nasalized'},
    'ˈẽ': {'symbol_type': 'phoneme',
            'vowel_consonant': 'vowel',
            'VUV': 'voiced',
            'vowel_frontness': 'front',
            'vowel_openness': 'open-mid',
            'vowel_roundedness': 'unrounded',
            'stress': 'primary_stress',
            'diacritic': 'nasalized'},
    'f': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'labiodental',
          'consonant_manner': 'fricative'},
    'g': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'velar',
          'consonant_manner': 'stop'},
    'h': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'glottal',
          'consonant_manner': 'fricative'},
    'i': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'close',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ˈi': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'close',
           'vowel_roundedness': 'unrounded',
           'stress': 'primary_stress'},
    'ˌi': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'close',
           'vowel_roundedness': 'unrounded',
           'stress': 'secondary_stress'},
    'j': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'palatal',
          'consonant_manner': 'approximant'},
    'k': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'velar',
          'consonant_manner': 'stop'},
    'l': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'lateral-approximant'},
    'l̩': {'symbol_type': 'phoneme',
           'vowel_consonant': 'consonant',
           'VUV': 'voiced',
           'consonant_place': 'alveolar',
           'consonant_manner': 'lateral-approximant',
           'diacritic': 'syllabic'},
    'm': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'bilabial',
          'consonant_manner': 'nasal'},
    'm̩': {'symbol_type': 'phoneme',
           'vowel_consonant': 'consonant',
           'VUV': 'voiced',
           'consonant_place': 'bilabial',
           'consonant_manner': 'nasal',
           'diacritic': 'syllabic'},
    'n': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'nasal'},
    'n̩': {'symbol_type': 'phoneme',
           'vowel_consonant': 'consonant',
           'VUV': 'voiced',
           'consonant_place': 'alveolar',
           'consonant_manner': 'nasal',
           'diacritic': 'syllabic'},
    'ɳ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'palatal',
          'consonant_manner': 'nasal'},
    'o': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'back',
          'vowel_openness': 'close-mid',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ˈo': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'back',
           'vowel_openness': 'close-mid',
           'vowel_roundedness': 'rounded',
           'stress': 'primary_stress'},
    'ɔ̃': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'back',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'rounded',
           'stress': 'unstressed',
           'diacritic': 'nasalized'},
    'ˈɔ̃': {'symbol_type': 'phoneme',
            'vowel_consonant': 'vowel',
            'VUV': 'voiced',
            'vowel_frontness': 'back',
            'vowel_openness': 'open-mid',
            'vowel_roundedness': 'rounded',
            'stress': 'primary_stress',
            'diacritic': 'nasalized'},
    'ˌɔ̃': {'symbol_type': 'phoneme',
            'vowel_consonant': 'vowel',
            'VUV': 'voiced',
            'vowel_frontness': 'back',
            'vowel_openness': 'open-mid',
            'vowel_roundedness': 'rounded',
            'stress': 'secondary_stress',
            'diacritic': 'nasalized'},
    'p': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'bilabial',
          'consonant_manner': 'stop'},
    'ɹ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'approximant'},
    'r': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'trill'},
    's': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'fricative'},
    't': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'stop'},
    't͡ʃ': {'symbol_type': 'phoneme',
            'vowel_consonant': 'consonant',
            'VUV': 'unvoiced',
            'consonant_place': 'postalveolar',
            'consonant_manner': 'affricate'},
    'u': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'back',
          'vowel_openness': 'close',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ˈu': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'back',
           'vowel_openness': 'close',
           'vowel_roundedness': 'rounded',
           'stress': 'primary_stress'},
    'ˌu': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'back',
           'vowel_openness': 'close',
           'vowel_roundedness': 'rounded',
           'stress': 'secondary_stress'},
    'v': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'labiodental',
          'consonant_manner': 'fricative'},
    'w': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'labial-velar',
          'consonant_manner': 'approximant'},
    'x': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'velar',
          'consonant_manner': 'fricative'},
    'z': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'fricative'},
    'ʀ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'uvular',
          'consonant_manner': 'trill'},
    'ø': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'close-mid',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ˈø': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'close-mid',
           'vowel_roundedness': 'rounded',
           'stress': 'primary_stress'},
    'ç': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'palatal',
          'consonant_manner': 'fricative'},
    'ã': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'open',
           'vowel_roundedness': 'unrounded',
           'stress': 'unstressed',
           'diacritic': 'nasalized'},
    'ɐ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'central',
          'vowel_openness': 'open',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ˈɐ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'central',
           'vowel_openness': 'open',
           'vowel_roundedness': 'unrounded',
           'stress': 'primary_stress'},
    'œ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'open-mid',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ˈœ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'open-mid',
           'vowel_roundedness': 'rounded',
           'stress': 'primary_stress'},
    'pf': {'symbol_type': 'phoneme',
           'vowel_consonant': 'consonant',
           'VUV': 'unvoiced',
           'consonant_place': 'bilabial',
           'consonant_manner': 'affricate'},
    'ts': {'symbol_type': 'phoneme',
           'vowel_consonant': 'consonant',
           'VUV': 'unvoiced',
           'consonant_place': 'alveolar',
           'consonant_manner': 'affricate'},
    'y': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'close',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ˈy': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front',
           'vowel_openness': 'close',
           'vowel_roundedness': 'rounded',
           'stress': 'primary_stress'},
    'ʏ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front_central',
          'vowel_openness': 'close_close-mid',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ˈʏ': {'symbol_type': 'phoneme',
           'vowel_consonant': 'vowel',
           'VUV': 'voiced',
           'vowel_frontness': 'front_central',
           'vowel_openness': 'close_close-mid',
           'vowel_roundedness': 'rounded',
           'stress': 'primary_stress'}
}
