#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Open-source resource provided by Papercup Technologies Limited
# Author: Marlene Staib
# MARY-TTS-TO-IPA MAPPING DICTIONARY FOR GERMAN

mary_to_ipa = {
    'e': 'e',
    's': 's',
    'p': 'p',
    '9': 'œ',
    'T': 'θ',
    'b': 'b',
    'N': 'ŋ',
    'u': 'u',
    'z': 'z',
    'v': 'v',
    '6': 'ɐ',
    'm': 'm',
    'a~': 'ã',
    't': 't',
    'aU': 'aʊ',
    'k': 'k',
    'S': 'ʃ',
    'Z': 'ʒ',
    'EI': 'ɛɪ',
    'OY': 'ɔɪ',
    'o~': 'õ',
    'a': 'a',
    'D': 'ð',
    '@': 'ə',
    'f': 'f',
    'n': 'n',
    'r': 'r',
    'x': 'x',
    'w': 'w',
    'j': 'j',
    'C': 'ç',
    'h': 'h',
    'O': 'ɔ',
    'R': 'ʀ',
    'ts': 'ts',
    'eI': 'eɪ',
    'E': 'ɛ',
    'e~': 'ẽ',
    'I': 'ɪ',
    'tS': 'tʃ',
    'd': 'd',
    'i': 'i',
    'y': 'y',
    'Y': 'ʏ',
    'l': 'l',
    'g': 'g',
    'aI': 'aɪ',
    'o': 'o',
    'pf': 'pf',
    'dZ': 'dʒ',
    'U': 'ʊ'
 }
